name: Deploy HTML to GitHub Pages

on:
  push:
    branches:
      - master  # or 'main' if your default branch is main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.Git_Token }}
          publish_dir: .  # Use './public' if your site files are inside a subfolder
          enable_jekyll: false
